version: "3.7"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: frontend-repository-procesos-politicas-TalentoHumano
    container_name: procesos-politicas-TalentoHumano-docker-nextjs-1
    ports:
      - "3007:3000"
    env_file:
      - .env
    networks:
      my_new_network:
        ipv4_address: 10.4.10.10  # Cambias la IP aquí

networks:
  my_new_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.0.0/16  # Mantienes esta subred
